theme: jekyll-theme-minimal
description: Jewelry making techniques using modern design tools. We cover the complete process, from conception and jewelry design to 3D printing.
show_downloads: false
show_title: false
logo: images/JewelryFab.png